server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    appname: item-service-provider
    virtualHostName: item-service-provider
    sercureVirtualHostName: item-service-provider
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cc.itemmanage
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zx_db?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full