server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    appname: user-service-provider
    virtualHostName: user-service-provider
    sercureVirtualHostName: user-feign-service-provider
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zx_db?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
#feign:
  #client:
    #config:
      #default:
        #connectTimeout: 5000
        #readTimeout: 5000
        #loggerLevel: full